<?php

interface DeviceInterface{
    public function volumeUp();
    public function volumeDown():bool;
    public function channelUp():bool;
    public function channelDown():bool;
}

abstract class DeviceAbstract implements DeviceInterface {
    public function volumeUp()
    {
        // TODO: Implement volumeUp() method.
    }

    public function volumeDown(): bool
    {
        // TODO: Implement volumeDown() method.
    }

    public function channelUp(): bool
    {
        // TODO: Implement channelUp() method.
    }

    public function channelDown(): bool
    {
        // TODO: Implement channelDown() method.
    }
}
class Samsung extends DeviceAbstract {

    public function volumeUp()
    {
        return true;
    }

    public function volumeDown(): bool
    {
        return true;
    }

    public function channelDown(): bool
    {
        return true;
    }

    public function channelUp(): bool
    {
        return true;
    }

}

class Lg extends DeviceAbstract {

    public function volumeUp()
    {
        parent::volumeUp(); // TODO: Change the autogenerated stub
    }

    public function volumeDown(): bool
    {
        parent::volumeDown(); // TODO: Change the autogenerated stub
    }

    public function channelDown(): bool
    {
        parent::channelDown(); // TODO: Change the autogenerated stub
    }

    public function channelUp(): bool
    {
        parent::channelUp(); // TODO: Change the autogenerated stub
    }

}

$samsung = new Samsung();
$samsung->volumeUp();
